# Generated by Django 4.0.6 on 2022-08-12 19:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('codLogin', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='factura_compra',
            fields=[
                ('ID_facPro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='juan', max_length=60)),
                ('apellido', models.CharField(default='juan', max_length=60)),
                ('correo', models.EmailField(default='juan@gmail.com', max_length=254)),
                ('direccion', models.CharField(default='cll', max_length=40)),
                ('ciudad', models.CharField(default='city', max_length=20)),
                ('telefono', models.CharField(default='111111', max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('forma_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('Id_cliecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('ID_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imageProd')),
                ('stock', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('descuento', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='factura_unidad',
            fields=[
                ('ID_factura', models.AutoField(primary_key=True, serialize=False)),
                ('valor_compra', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('Id_facturaProductos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.factura_compra')),
                ('Id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.producto')),
            ],
        ),
    ]
