# Generated by Django 4.0.6 on 2022-08-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_unidad',
            old_name='Id_facturaProductos',
            new_name='Id_facturaCompra',
        ),
    ]
